name: Build and Release Halo EPD Firmware

env:
  DEVICE_NAME: halo-epd

on:
  push:
    paths:
      - 'E-Paper/**'
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of the firmware to build'
        required: true
  release:
    types: [published]

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    permissions:
      contents: write
    outputs:
      release_skipped: ${{ steps.check_tag.outputs.exists }}
      version: ${{ steps.get_version.outputs.project_version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.7

      - name: Get Version
        id: get_version
        run: |
          version=$(awk '/substitutions:/ {found=1} found && /version:/ {print $2; exit}' E-Paper/Waveshare_BWR/V1/Firmware/ESPHome/Halo_EPD-Core.yaml | tr -d '"')
          echo "project_version=$version" >> $GITHUB_ENV
          echo "project_version=$version" >> "$GITHUB_OUTPUT"

      - name: Check if Tag Exists
        id: check_tag
        run: |
          if git ls-remote --tags origin | grep -q "refs/tags/${{ env.project_version }}$"; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Create GitHub Release
        if: steps.check_tag.outputs.exists == 'false'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: ${{ env.project_version }}
          release_name: "Release ${{ env.project_version }}"
          draft: false
          prerelease: false
          body: "Auto-generated release from GitHub Actions."
